import { OpenAPIV3 } from 'openapi-types';
import { doc } from 'prettier';
import { DocumentParser } from '../../src/parsers/DocumentParser';
import { TypeDocument } from '../../src/parsers/types';
import document from '../files/petStore3.openapi.json' assert { type: 'json' };
import { writeFile } from '../helpers';

test('DocumentParser', () => {
  const parser = new DocumentParser();
  parser.read(document as unknown as OpenAPIV3.Document);
  const types = parser.parse();
  writeFile('petStore3.types.json', types);
  expect(types).toMatchInlineSnapshot(`
    {
      "components": [
        {
          "children": [
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "Palo Alto",
              "format": undefined,
              "kind": "origin",
              "name": "city",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "CA",
              "format": undefined,
              "kind": "origin",
              "name": "state",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "437 Lytton",
              "format": undefined,
              "kind": "origin",
              "name": "street",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "94301",
              "format": undefined,
              "kind": "origin",
              "name": "zip",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "Address",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": "int32",
              "kind": "origin",
              "name": "code",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "message",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "type",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "ApiResponse",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 1,
              "format": "int64",
              "kind": "origin",
              "name": "id",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "Dogs",
              "format": undefined,
              "kind": "origin",
              "name": "name",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "Category",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "children": [
                {
                  "kind": "alias",
                  "name": "address[]",
                  "origin": "Address",
                  "props": [],
                  "ref": "#/components/schemas/Address",
                  "refAble": false,
                  "required": true,
                  "target": "Address",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "address",
              "required": false,
              "title": undefined,
              "type": "array",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 100000,
              "format": "int64",
              "kind": "origin",
              "name": "id",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "fehguy",
              "format": undefined,
              "kind": "origin",
              "name": "username",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "Customer",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "complete",
              "required": false,
              "title": undefined,
              "type": "boolean",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 10,
              "format": "int64",
              "kind": "origin",
              "name": "id",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 198772,
              "format": "int64",
              "kind": "origin",
              "name": "petId",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 7,
              "format": "int32",
              "kind": "origin",
              "name": "quantity",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": "date-time",
              "kind": "origin",
              "name": "shipDate",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": "Order Status",
              "enum": [
                "placed",
                "approved",
                "delivered",
              ],
              "example": "approved",
              "format": undefined,
              "kind": "origin",
              "name": "status",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "Order",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "kind": "alias",
              "name": "category",
              "origin": "Category",
              "props": [],
              "ref": "#/components/schemas/Category",
              "refAble": false,
              "required": false,
              "target": "Category",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 10,
              "format": "int64",
              "kind": "origin",
              "name": "id",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "doggie",
              "format": undefined,
              "kind": "origin",
              "name": "name",
              "required": true,
              "title": undefined,
              "type": "string",
            },
            {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": undefined,
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "photoUrls[]",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "photoUrls",
              "required": true,
              "title": undefined,
              "type": "array",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": "pet status in the store",
              "enum": [
                "available",
                "pending",
                "sold",
              ],
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "status",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "children": [
                {
                  "kind": "alias",
                  "name": "tags[]",
                  "origin": "Tag",
                  "props": [],
                  "ref": "#/components/schemas/Tag",
                  "refAble": false,
                  "required": true,
                  "target": "Tag",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "tags",
              "required": false,
              "title": undefined,
              "type": "array",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "Pet",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": "int64",
              "kind": "origin",
              "name": "id",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "name",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "Tag",
          "required": false,
          "title": undefined,
          "type": "object",
        },
        {
          "children": [
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "john@email.com",
              "format": undefined,
              "kind": "origin",
              "name": "email",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "John",
              "format": undefined,
              "kind": "origin",
              "name": "firstName",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": 10,
              "format": "int64",
              "kind": "origin",
              "name": "id",
              "required": false,
              "title": undefined,
              "type": "number",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "James",
              "format": undefined,
              "kind": "origin",
              "name": "lastName",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "12345",
              "format": undefined,
              "kind": "origin",
              "name": "password",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "12345",
              "format": undefined,
              "kind": "origin",
              "name": "phone",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": "theUser",
              "format": undefined,
              "kind": "origin",
              "name": "username",
              "required": false,
              "title": undefined,
              "type": "string",
            },
            {
              "default": undefined,
              "deprecated": undefined,
              "description": "User Status",
              "enum": undefined,
              "example": 1,
              "format": "int32",
              "kind": "origin",
              "name": "userStatus",
              "required": false,
              "title": undefined,
              "type": "number",
            },
          ],
          "default": undefined,
          "deprecated": undefined,
          "description": undefined,
          "enum": undefined,
          "example": undefined,
          "format": undefined,
          "kind": "origin",
          "name": "User",
          "required": false,
          "title": undefined,
          "type": "object",
        },
      ],
      "info": {
        "baseURL": "/api/v3",
        "description": "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)",
        "title": "Swagger Petstore - OpenAPI 3.0",
        "version": "1.0.17",
      },
      "paths": [
        {
          "deprecated": undefined,
          "description": "Add a new pet to the store",
          "method": "post",
          "name": "addPet",
          "request": {
            "body": {
              "kind": "alias",
              "name": "AddPetReqData",
              "origin": "Pet",
              "props": [],
              "ref": "#/components/schemas/Pet",
              "refAble": false,
              "required": true,
              "target": "Pet",
            },
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "AddPetResData",
              "origin": "Pet",
              "props": [],
              "ref": "#/components/schemas/Pet",
              "refAble": false,
              "required": true,
              "target": "Pet",
            },
          },
          "title": "Add a new pet to the store",
          "url": "/pet",
        },
        {
          "deprecated": undefined,
          "description": "Update an existing pet by Id",
          "method": "put",
          "name": "updatePet",
          "request": {
            "body": {
              "kind": "alias",
              "name": "UpdatePetReqData",
              "origin": "Pet",
              "props": [],
              "ref": "#/components/schemas/Pet",
              "refAble": false,
              "required": true,
              "target": "Pet",
            },
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "UpdatePetResData",
              "origin": "Pet",
              "props": [],
              "ref": "#/components/schemas/Pet",
              "refAble": false,
              "required": true,
              "target": "Pet",
            },
          },
          "title": "Update an existing pet",
          "url": "/pet",
        },
        {
          "deprecated": undefined,
          "description": "",
          "method": "delete",
          "name": "deletePet",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "Pet id to delete",
                  "enum": undefined,
                  "example": undefined,
                  "format": "int64",
                  "kind": "origin",
                  "name": "petId",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "kind": "origin",
              "name": "DeletePetReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": undefined,
          },
          "title": "Deletes a pet",
          "url": "/pet/{petId}",
        },
        {
          "deprecated": undefined,
          "description": "Returns a single pet",
          "method": "get",
          "name": "getPetById",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "ID of pet to return",
                  "enum": undefined,
                  "example": undefined,
                  "format": "int64",
                  "kind": "origin",
                  "name": "petId",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "kind": "origin",
              "name": "GetPetByIdReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "GetPetByIdResData",
              "origin": "Pet",
              "props": [],
              "ref": "#/components/schemas/Pet",
              "refAble": false,
              "required": true,
              "target": "Pet",
            },
          },
          "title": "Find pet by ID",
          "url": "/pet/{petId}",
        },
        {
          "deprecated": undefined,
          "description": "",
          "method": "post",
          "name": "updatePetWithForm",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "ID of pet that needs to be updated",
                  "enum": undefined,
                  "example": undefined,
                  "format": "int64",
                  "kind": "origin",
                  "name": "petId",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "kind": "origin",
              "name": "UpdatePetWithFormReqPath",
              "required": true,
              "type": "object",
            },
            "query": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "Name of pet that needs to be updated",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "name",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "Status of pet that needs to be updated",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "status",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "UpdatePetWithFormReqParams",
              "required": false,
              "type": "object",
            },
          },
          "response": {
            "body": undefined,
          },
          "title": "Updates a pet in the store with form data",
          "url": "/pet/{petId}",
        },
        {
          "deprecated": undefined,
          "description": "",
          "method": "post",
          "name": "uploadFile",
          "request": {
            "body": {
              "kind": "alias",
              "name": "UploadFileReqData",
              "origin": "Blob",
              "props": [],
              "refAble": false,
              "required": true,
              "target": "Blob",
            },
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "ID of pet to update",
                  "enum": undefined,
                  "example": undefined,
                  "format": "int64",
                  "kind": "origin",
                  "name": "petId",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "kind": "origin",
              "name": "UploadFileReqPath",
              "required": true,
              "type": "object",
            },
            "query": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "Additional Metadata",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "additionalMetadata",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "UploadFileReqParams",
              "required": false,
              "type": "object",
            },
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "UploadFileResData",
              "origin": "ApiResponse",
              "props": [],
              "ref": "#/components/schemas/ApiResponse",
              "refAble": false,
              "required": true,
              "target": "ApiResponse",
            },
          },
          "title": "uploads an image",
          "url": "/pet/{petId}/uploadImage",
        },
        {
          "deprecated": undefined,
          "description": "Multiple status values can be provided with comma separated strings",
          "method": "get",
          "name": "findPetsByStatus",
          "request": {
            "body": undefined,
            "path": undefined,
            "query": {
              "children": [
                {
                  "default": "available",
                  "deprecated": undefined,
                  "description": "Status values that need to be considered for filter",
                  "enum": [
                    "available",
                    "pending",
                    "sold",
                  ],
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "status",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "FindPetsByStatusReqParams",
              "required": false,
              "type": "object",
            },
          },
          "response": {
            "body": {
              "children": [
                {
                  "kind": "alias",
                  "name": "FindPetsByStatusResData[]",
                  "origin": "Pet",
                  "props": [],
                  "ref": "#/components/schemas/Pet",
                  "refAble": false,
                  "required": true,
                  "target": "Pet",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "FindPetsByStatusResData",
              "required": false,
              "title": undefined,
              "type": "array",
            },
          },
          "title": "Finds Pets by status",
          "url": "/pet/findByStatus",
        },
        {
          "deprecated": undefined,
          "description": "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
          "method": "get",
          "name": "findPetsByTags",
          "request": {
            "body": undefined,
            "path": undefined,
            "query": {
              "children": [
                {
                  "children": [
                    {
                      "default": undefined,
                      "deprecated": undefined,
                      "description": undefined,
                      "enum": undefined,
                      "example": undefined,
                      "format": undefined,
                      "kind": "origin",
                      "name": "tags[]",
                      "required": false,
                      "title": undefined,
                      "type": "string",
                    },
                  ],
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "Tags to filter by",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "tags",
                  "required": false,
                  "title": undefined,
                  "type": "array",
                },
              ],
              "kind": "origin",
              "name": "FindPetsByTagsReqParams",
              "required": false,
              "type": "object",
            },
          },
          "response": {
            "body": {
              "children": [
                {
                  "kind": "alias",
                  "name": "FindPetsByTagsResData[]",
                  "origin": "Pet",
                  "props": [],
                  "ref": "#/components/schemas/Pet",
                  "refAble": false,
                  "required": true,
                  "target": "Pet",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "FindPetsByTagsResData",
              "required": false,
              "title": undefined,
              "type": "array",
            },
          },
          "title": "Finds Pets by tags",
          "url": "/pet/findByTags",
        },
        {
          "deprecated": undefined,
          "description": "Returns a map of status codes to quantities",
          "method": "get",
          "name": "getInventory",
          "request": {
            "body": undefined,
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": undefined,
                  "enum": undefined,
                  "example": undefined,
                  "format": "int32",
                  "kind": "origin",
                  "name": "[key: string]",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "GetInventoryResData",
              "required": false,
              "title": undefined,
              "type": "object",
            },
          },
          "title": "Returns pet inventories by status",
          "url": "/store/inventory",
        },
        {
          "deprecated": undefined,
          "description": "Place a new order in the store",
          "method": "post",
          "name": "placeOrder",
          "request": {
            "body": {
              "kind": "alias",
              "name": "PlaceOrderReqData",
              "origin": "Order",
              "props": [],
              "ref": "#/components/schemas/Order",
              "refAble": false,
              "required": true,
              "target": "Order",
            },
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "PlaceOrderResData",
              "origin": "Order",
              "props": [],
              "ref": "#/components/schemas/Order",
              "refAble": false,
              "required": true,
              "target": "Order",
            },
          },
          "title": "Place an order for a pet",
          "url": "/store/order",
        },
        {
          "deprecated": undefined,
          "description": "For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors",
          "method": "delete",
          "name": "deleteOrder",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "ID of the order that needs to be deleted",
                  "enum": undefined,
                  "example": undefined,
                  "format": "int64",
                  "kind": "origin",
                  "name": "orderId",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "kind": "origin",
              "name": "DeleteOrderReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": undefined,
          },
          "title": "Delete purchase order by ID",
          "url": "/store/order/{orderId}",
        },
        {
          "deprecated": undefined,
          "description": "For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.",
          "method": "get",
          "name": "getOrderById",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "ID of order that needs to be fetched",
                  "enum": undefined,
                  "example": undefined,
                  "format": "int64",
                  "kind": "origin",
                  "name": "orderId",
                  "required": true,
                  "title": undefined,
                  "type": "number",
                },
              ],
              "kind": "origin",
              "name": "GetOrderByIdReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "GetOrderByIdResData",
              "origin": "Order",
              "props": [],
              "ref": "#/components/schemas/Order",
              "refAble": false,
              "required": true,
              "target": "Order",
            },
          },
          "title": "Find purchase order by ID",
          "url": "/store/order/{orderId}",
        },
        {
          "deprecated": undefined,
          "description": "This can only be done by the logged in user.",
          "method": "post",
          "name": "createUser",
          "request": {
            "body": {
              "kind": "alias",
              "name": "CreateUserReqData",
              "origin": "User",
              "props": [],
              "ref": "#/components/schemas/User",
              "refAble": false,
              "required": true,
              "target": "User",
            },
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": undefined,
          },
          "title": "Create user",
          "url": "/user",
        },
        {
          "deprecated": undefined,
          "description": "This can only be done by the logged in user.",
          "method": "delete",
          "name": "deleteUser",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "The name that needs to be deleted",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "username",
                  "required": true,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "DeleteUserReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": undefined,
          },
          "title": "Delete user",
          "url": "/user/{username}",
        },
        {
          "deprecated": undefined,
          "description": "",
          "method": "get",
          "name": "getUserByName",
          "request": {
            "body": undefined,
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "The name that needs to be fetched. Use user1 for testing. ",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "username",
                  "required": true,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "GetUserByNameReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "GetUserByNameResData",
              "origin": "User",
              "props": [],
              "ref": "#/components/schemas/User",
              "refAble": false,
              "required": true,
              "target": "User",
            },
          },
          "title": "Get user by user name",
          "url": "/user/{username}",
        },
        {
          "deprecated": undefined,
          "description": "This can only be done by the logged in user.",
          "method": "put",
          "name": "updateUser",
          "request": {
            "body": {
              "kind": "alias",
              "name": "UpdateUserReqData",
              "origin": "User",
              "props": [],
              "ref": "#/components/schemas/User",
              "refAble": false,
              "required": true,
              "target": "User",
            },
            "path": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "name that need to be deleted",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "username",
                  "required": true,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "UpdateUserReqPath",
              "required": true,
              "type": "object",
            },
            "query": undefined,
          },
          "response": {
            "body": undefined,
          },
          "title": "Update user",
          "url": "/user/{username}",
        },
        {
          "deprecated": undefined,
          "description": "Creates list of users with given input array",
          "method": "post",
          "name": "createUsersWithListInput",
          "request": {
            "body": {
              "children": [
                {
                  "kind": "alias",
                  "name": "CreateUsersWithListInputReqData[]",
                  "origin": "User",
                  "props": [],
                  "ref": "#/components/schemas/User",
                  "refAble": false,
                  "required": true,
                  "target": "User",
                },
              ],
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "CreateUsersWithListInputReqData",
              "required": false,
              "title": undefined,
              "type": "array",
            },
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": {
              "kind": "alias",
              "name": "CreateUsersWithListInputResData",
              "origin": "User",
              "props": [],
              "ref": "#/components/schemas/User",
              "refAble": false,
              "required": true,
              "target": "User",
            },
          },
          "title": "Creates list of users with given input array",
          "url": "/user/createWithList",
        },
        {
          "deprecated": undefined,
          "description": "",
          "method": "get",
          "name": "loginUser",
          "request": {
            "body": undefined,
            "path": undefined,
            "query": {
              "children": [
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "The user name for login",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "username",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
                {
                  "default": undefined,
                  "deprecated": undefined,
                  "description": "The password for login in clear text",
                  "enum": undefined,
                  "example": undefined,
                  "format": undefined,
                  "kind": "origin",
                  "name": "password",
                  "required": false,
                  "title": undefined,
                  "type": "string",
                },
              ],
              "kind": "origin",
              "name": "LoginUserReqParams",
              "required": false,
              "type": "object",
            },
          },
          "response": {
            "body": {
              "default": undefined,
              "deprecated": undefined,
              "description": undefined,
              "enum": undefined,
              "example": undefined,
              "format": undefined,
              "kind": "origin",
              "name": "LoginUserResData",
              "required": false,
              "title": undefined,
              "type": "string",
            },
          },
          "title": "Logs user into the system",
          "url": "/user/login",
        },
        {
          "deprecated": undefined,
          "description": "",
          "method": "get",
          "name": "logoutUser",
          "request": {
            "body": undefined,
            "path": undefined,
            "query": undefined,
          },
          "response": {
            "body": undefined,
          },
          "title": "Logs out current logged in user session",
          "url": "/user/logout",
        },
      ],
    }
  `);
});
