import { OpenAPIV3 } from 'openapi-types';

export const HTTP_METHODS: OpenAPIV3.HttpMethods[] = [
  OpenAPIV3.HttpMethods.DELETE,
  OpenAPIV3.HttpMethods.GET,
  OpenAPIV3.HttpMethods.HEAD,
  OpenAPIV3.HttpMethods.OPTIONS,
  OpenAPIV3.HttpMethods.PATCH,
  OpenAPIV3.HttpMethods.POST,
  OpenAPIV3.HttpMethods.PUT,
  OpenAPIV3.HttpMethods.TRACE,
];

export const JSON_MIME = 'application/json';
export const BLOB_MIME = 'application/octet-stream';

// 内部类型名称，文档里如果重复了会生成新的唯一值
export const INTERNAL_TYPE_NAMES = [
  // native
  'Blob',
  // @ref ComponentsWriter
  'OneOf',
  // @ref PathsWriter
  'axios',
  'request',
  'DELETE',
  'GET',
  'HEAD',
  'OPTIONS',
  'PATCH',
  'POST',
  'PUT',
  'TRACE',
  'resolveURL',
  'BASE_URL',
  'AxiosPromise',
  'AxiosRequestConfig',
];

// @ref https://www.w3schools.com/js/js_reserved.asp
export const JS_RESERVED_NAMES = [
  'abstract',
  'arguments',
  'await',
  'boolean',
  'break',
  'byte',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'double',
  'else',
  'enum',
  'eval',
  'export',
  'extends',
  'false',
  'final',
  'finally',
  'float',
  'for',
  'function',
  'goto',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'int',
  'interface',
  'let',
  'long',
  'native',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'static',
  'super',
  'switch',
  'synchronized',
  'this',
  'throw',
  'throws',
  'transient',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'volatile',
  'while',
  'with',
  'yield',
  'abstract',
  'boolean',
  'byte',
  'char',
  'double',
  'final',
  'float',
  'goto',
  'int',
  'long',
  'native',
  'short',
  'synchronized',
  'throws',
  'transient',
  'volatile',
];
