name: node env

permissions:
  contents: read

jobs:
  node-env:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created
    steps:
      - run: sudo timedatectl set-timezone Asia/Shanghai
      - run: timedatectl
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: '**/package-lock.json'
