# 如果是开发合并请求到主干，则会根据约定式提交创建一个 releasePR，是一个新版本合并请求。
# 如果是新版本合并请求合并到主干，则会触发版本发布到 npm/github 等仓库。

name: release please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          bump-minor-pre-major: true

  test-coverage:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-env
      - run: npm ci
      - run: npm run test-coverage
      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/lcov.info

  publish-npm:
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-env
      - run: npm ci
      - run: npm run build
      - uses: ./.github/actions/npm-publish
        with:
          type: npm
          token: ${{ secrets.NPM_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-env
      - run: npm ci
      - run: npm run build
      - uses: ./.github/actions/npm-publish
        with:
          type: github
