name: release please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: ./.github/common-workflows/node-env.yml
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
  test:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created
    steps:
      - uses: ./.github/common-workflows/node-env.yml
      - run: npm ci
      - run: npm run test
      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/lcov.info
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: ./.github/common-workflows/node-env.yml
      - run: npm ci
      - run: npm run build
      - run: npm publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: jaywcjlove/github-action-package@main
        id: pkg
      - run: curl --silent -X PUT https://registry-direct.npmmirror.com/${{ steps.pkg.outputs.name }}/sync?sync_upstream=true
        name: Sync the new version to npmmirror.com
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
      - run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
